### ISSUE TITLE
 can you make it a cmake build? 

### ISSUE THREAD

**Issue by tjnapster555** [jmemmons/lib-database-management-system#1]
Hi its great program and i just want to know can you make a cmake file for it?

**Comment by jmemmons** [comment]
Yes I will make a CMake build for this tonight. I'm currently updating the program for Windows users as well since there was an issue preventing it from running.

**Comment by jmemmons** [comment]
CMake build is now live for Linux. I will complete the Windows version when I have time this evening. I'm closing the issue now. Let me know if you need anything else.

**Comment by tjnapster555** [comment]
thanks for reply
