### ISSUE TITLE
Help in my database project 

### ISSUE THREAD

**Issue by yottabytedev** [jmemmons/lib-database-management-system#2]
Hey buddy ,
           I am working on my colleges accounts management system . I am new in database management system . So can you help me in my project by guiding and contributing.
thanks

**Comment by jmemmons** [comment]
Sorry I'm just now seeing this, I've been working on a huge project at work and didn't have any time to get on here. If you still have an issue, I can help you. Any details would be helpful. Keep in mind, I did not write this library, I found it on YouTube and simply hosted it for others.

**Comment by yottabytedev** [comment]
Thanks for your reply . Sorry for replying late . No problem If you are busy . Can you suggest where should I start and proceed . And please suggest some **sites** from which I can have idea .
Thanks in advance .
